name: Sync Fork

on:
  schedule:
    - cron: '* */6 * * *' # Run every 6 hour
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: llvm
